from django.contrib.auth.decorators import login_required
from django.contrib.sites import requests
import requests as r
from django.db.models import Sum, Avg
from django.http import JsonResponse, HttpResponseForbidden, HttpRequest
from django.shortcuts import render, redirect
from rest_framework.decorators import permission_classes
from rest_framework_api_key.models import APIKey
import json

from rest_framework_api_key.permissions import HasAPIKey

from .models import ProjectMetrics, OrganizationAPIKey, Organization, User, OrganizationMember, Project
from django.views.decorators.csrf import  csrf_exempt
from django_ratelimit.decorators import ratelimit
import os
from django.contrib.auth import authenticate, login


@login_required
def getApiKey(request):
    return render(request, "GetApiKey.html")


@login_required
def generate(request): #proxy
    res = r.post(
        os.getenv("API_KEY"), #generate api key
    )
    return JsonResponse(res.json())

@login_required
@ratelimit(key='user', rate='5/h', method='POST')
def generateApiKey(request):
    try:
        user = request.user
        # Get user's organization
        if not user.organization:
            return JsonResponse({"error": "You must be in an organization to generate API keys"}, status=400)

        # Generate the key
        api_key, key = OrganizationAPIKey.objects.create_key(
            organization=user.organization,
            created_by=user,
            name=f"Generated by {user.email}"
        )

        return JsonResponse({"key": key})
    except OrganizationMember.DoesNotExist:
        return JsonResponse({"error": "You are not a member of this organization"}, status=400)
    except Exception as e:
        return JsonResponse({"error": str(e)}, status=500)


@csrf_exempt
@permission_classes([HasAPIKey])
def addHistory(request):
    if request.method == "POST":
        data = json.loads(request.body)
        try:
            project = Project.objects.get(id=data["project_id"])
            ProjectMetrics.objects.create(
                project=project,
                errors=data["errors"],
                successes=data["success"],
                total_requests=data["total"],
                avg_latency=data["avg_latency_ms"],
                p95_latency=data["p95_latency_ms"],
                location=data["location"]
            )
        except Exception as e:
            return JsonResponse({"error": str(e)})

@csrf_exempt
@permission_classes([HasAPIKey])
def fetchHistory(request):
    model_data = ProjectMetrics.objects.all()
    try:
        data = []
        for m in model_data:
            data.append({
                "project_name": m.project.name,
                "project_id": m.project_id,
                "avg_latency_ms": m.avg_latency,
                "p95_latency_ms": m.p95_latency,
                "success": m.successes,
                "errors": m.errors,
                "total": m.total_requests,
                "location": m.location
            })

        return JsonResponse(data, safe=False)
    except Exception as e:
        return JsonResponse({"error": str(e)})

@login_required
def dashboard(request):
    user = request.user

    if not user.organization:
        return redirect('login')

    # Get projects with aggregated metrics
    projects = Project.objects.filter(
        organization=user.organization,
        active=True
    ).annotate(
        total_requests=Sum('metrics__total_requests'),
        total_errors=Sum('metrics__errors'),
        total_success=Sum('metrics__successes'),
        avg_latency=Avg('metrics__avg_latency'),
        p95_latency=Avg('metrics__p95_latency')
    ).order_by('-created_at')

    # Check if admin
    try:
        member = OrganizationMember.objects.get(
            user=user,
            organization=user.organization
        )
        is_admin = member.role in ['owner', 'admin']
    except OrganizationMember.DoesNotExist:
        is_admin = False

    context = {
        'projects': projects,
        'is_admin': is_admin,
    }

    return render(request, 'dashboard.html', context)

def createProject(request):
    if request.method == "POST":
        data = json.loads(request.body)
        try:
            project_id = 1
            if Project.objects.exists():
                project_id = Project.objects.latest('id').id + 1
            project = Project.objects.create(
                name=data["name"],
                project_id=str(project_id),
                organization=request.user.organization,
                active=True
            )
            return JsonResponse({"success": True, "project_id": project.id})
        except Exception as e:
            return JsonResponse({"error": str(e)}, status=400)

def deleteProject(request):
    if request.method != "DELETE":
        data = json.loads(request.body)
        user = request.user

        if not user.organization:
            return JsonResponse({'error': 'No organization'}, status=400)

        isAdmin = ['owner', 'admin']
        if request.user.organizationmember_set.filter(role__in=isAdmin).exists():
            try:
                Project.objects.get(id=data["project_id"], organization=user.organization).delete()
                return JsonResponse({"success": True})
            except Exception as e:
                return JsonResponse({"error": str(e)}, status=400)

def login_page(request):
    return render(request, 'login.html')

def signupLogin(request):
    if request.method == "POST":
        try:
            data = json.loads(request.body)
            email = data.get('email')
            password = data["password"]
            inviteCode = data["invite_code"]
            user = authenticate(request, username=email, password=password)

            # If user exist login
            if user is not None:
                login(request, user)
                return JsonResponse({"success": True})

            if inviteCode:
                #join org
                try:
                    org = Organization.objects.get(invite_code=inviteCode)
                    user = User.objects.create_user(
                        username=email,
                        email=email,
                        password=password,
                        organization=org
                    )
                    OrganizationMember.objects.create(
                        user=user,
                        organization=org,
                        role='member'
                    )
                    login(request, user)
                    return JsonResponse({"success": True})
                except:
                    return JsonResponse({"error": "Invalid API key"}, status=400)
            else:
                #make org
                try:
                    user = User.objects.create_user(
                        username=email,
                        email=email,
                        password=password
                    )
                    org = Organization.objects.create(
                        name=f"{email}'s Organization",
                    )
                    user.organization = org
                    user.save()

                    OrganizationMember.objects.create(
                        user=user,
                        organization=org,
                        role='owner'
                    )

                    login(request, user)
                    return JsonResponse({"success": True})

                except Exception as e:
                    return JsonResponse({"error": str(e)}, status=400)

        except Exception as e:
            return JsonResponse({"error": str(e)}, status=400)


