from django.contrib.auth.decorators import login_required
from django.contrib.sites import requests
from django.http import JsonResponse, HttpResponseForbidden
from django.shortcuts import render
from rest_framework.decorators import permission_classes
from rest_framework_api_key.models import APIKey
import json

from rest_framework_api_key.permissions import HasAPIKey

from .models import ProjectMetrics, OrganizationAPIKey, Organization, User, OrganizationMember, Project
from django.views.decorators.csrf import ensure_csrf_cookie, csrf_exempt
from django_ratelimit.decorators import ratelimit
import os
from django.contrib.auth import authenticate, login


@login_required
def getApiKey(request):
    return render(request, "GetApiKey.html")


@login_required
def generate(request): #proxy
    res = requests.post(
        os.getenv("API_KEY"), #generate api key
    )
    return JsonResponse(res.json())

@login_required
@ratelimit(key='user', rate='5/h', method='POST')
def generateApiKey(request):
    try:
        user = request.user
        # Get user's organization
        if not user.organization:
            return JsonResponse({"error": "You must be in an organization to generate API keys"}, status=400)

        # Generate the key
        api_key, key = OrganizationAPIKey.objects.create_key(
            organization=user.organization,
            created_by=user,
            name=f"Generated by {user.email}"
        )

        return JsonResponse({"key": key})
    except OrganizationMember.DoesNotExist:
        return JsonResponse({"error": "You are not a member of this organization"}, status=400)
    except Exception as e:
        return JsonResponse({"error": str(e)}, status=500)


@csrf_exempt
@permission_classes([HasAPIKey])
def addHistory(request):
    if request.method == "POST":
        data = json.loads(request.body)
        try:
            ProjectMetrics.objects.create(
                project=...,  # need to link to project
                errors=data["errors"],
                successes=data["success"],
                total_requests=data["total"],
                avg_latency=data["avg_latency_ms"],
                p95_latency=data["p95_latency_ms"],
                location=data["location"]
            )
        except Exception as e:
            return JsonResponse({"error": str(e)})

@csrf_exempt
@permission_classes([HasAPIKey])
def fetchHistory(request):
    model_data = ProjectMetrics.objects.all()
    try:
        data = []
        for m in model_data:
            data.append({
                "project_name": m.project.name,
                "project_id": m.project_id,
                "avg_latency_ms": m.avg_latency,
                "p95_latency_ms": m.p95_latency,
                "success": m.successes,
                "errors": m.errors,
                "total": m.total_requests,
                "location": m.location
            })

        return JsonResponse(data, safe=False)
    except Exception as e:
        return JsonResponse({"error": str(e)})

@login_required
def dashboard(request):
    try:
        user = request.user

        if not user.organization:
            return JsonResponse({"error": "You must be in an organization to view this page"}, status=400)

        #will be used later for actual stuff like revoking keys, deleteing/ adding projs, etc
        member = OrganizationMember.objects.get(user=user, organization=user.organization)
    except Exception as e:
        return JsonResponse({"error": str(e)}, status=400)



def login_page(request):
    return render(request, 'login.html')

def signupLogin(request):
    if request.method == "POST":
        try:
            data = json.loads(request.body)
            email = data.get('email')
            password = data["password"]
            inviteCode = data["invite_code"]
            user = authenticate(request, username=email, password=password)

            # If user exist login
            if user is not None:
                login(request, user)
                return JsonResponse({"success": True})

            if inviteCode:
                #join org
                try:
                    org = Organization.objects.get(invite_code=inviteCode)
                    user = User.objects.create_user(
                        username=email,
                        email=email,
                        password=password,
                        organization=org
                    )
                    OrganizationMember.objects.create(
                        user=user,
                        organization=org,
                        role='member'
                    )
                    login(request, user)
                    return JsonResponse({"success": True})
                except:
                    return JsonResponse({"error": "Invalid API key"}, status=400)
            else:
                #make org
                try:
                    user = User.objects.create_user(
                        username=email,
                        email=email,
                        password=password
                    )
                    org = Organization.objects.create(
                        name=f"{email}'s Organization",
                        owner=user
                    )
                    user.organization = org
                    user.save()

                    OrganizationMember.objects.create(
                        user=user,
                        organization=org,
                        role='owner'
                    )

                    login(request, user)
                    return JsonResponse({"success": True})

                except Exception as e:
                    return JsonResponse({"error": str(e)}, status=400)

        except Exception as e:
            return JsonResponse({"error": str(e)}, status=400)


